source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPMediaPicker_Example', :exclusive => true do
  pod 'POPMediaPicker', :path => '../'
end

target 'POPMediaPicker_Tests', :exclusive => true do
  pod 'POPMediaPicker', :path => '../'

  
end
